"""Add orders

Revision ID: 93377e4c0c46
Revises: 848d67ff6fa4
Create Date: 2024-02-18 01:06:34.085943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93377e4c0c46'
down_revision = '848d67ff6fa4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
