"""Add edit PK basket

Revision ID: 45c86ca587c1
Revises: a7a4eddb2b35
Create Date: 2024-02-17 19:54:46.562159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c86ca587c1'
down_revision = 'a7a4eddb2b35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('basket', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('basket', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('basket', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('basket', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
