"""Add product

Revision ID: 6f533f405102
Revises: d7f25f9aaaeb
Create Date: 2024-02-14 01:25:27.510383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f533f405102'
down_revision = 'd7f25f9aaaeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
