"""Add edit PK basket

Revision ID: 64dbe9e2f03b
Revises: 45c86ca587c1
Create Date: 2024-02-17 20:01:27.354869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dbe9e2f03b'
down_revision = '45c86ca587c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
