"""Add orders

Revision ID: ced6f43055e9
Revises: edd19b76be72
Create Date: 2024-02-18 03:14:54.512659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced6f43055e9'
down_revision = 'edd19b76be72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('timestamp', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'timestamp')
    # ### end Alembic commands ###
