"""Add orders

Revision ID: edd19b76be72
Revises: 93377e4c0c46
Create Date: 2024-02-18 01:37:38.149389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd19b76be72'
down_revision = '93377e4c0c46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
